# Decision Tree

Regina Ceballos Mondrag√≥n

147663

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.path as pth
from sklearn.model_selection import train_test_split
from sklearn import tree
import graphviz
import pydotplus

## Data download

In [2]:
df = pd.read_csv('zoo.csv')
X_train, X_test, Y_train, Y_test = train_test_split(df[df.columns[1:-1]], df[['class_type']], train_size=0.75)
X_train, X_test, Y_train, Y_test = np.asarray(X_train), np.asarray(X_test), np.asarray(Y_train), np.asarray(Y_test)
df.describe()

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/model_selection/_split.py:2010: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
count,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000,101.000000
mean,0.425743,0.198020,0.584158,0.405941,0.237624,0.356436,0.554455,0.603960,0.821782,0.792079,0.079208,0.168317,2.841584,0.742574,0.128713,0.435644,2.831683
std,0.496921,0.400495,0.495325,0.493522,0.427750,0.481335,0.499505,0.491512,0.384605,0.407844,0.271410,0.376013,2.033385,0.439397,0.336552,0.498314,2.102709
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000,0.000000,2.000000
75%,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.000000,1.000000,0.000000,1.000000,4.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.000000,1.000000,1.000000,1.000000,7.000000

## Tree training

In [3]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, Y_train)

In [7]:
print("Importance of features")
print(clf.feature_importances_)
print("Accuracy")
print(clf.score(X_test, Y_test))

Importance of features
[ 0.          0.21252662  0.02291476  0.36667512  0.08337289  0.02291476
  0.00802016  0.          0.08865147  0.          0.          0.17200948
  0.02291476  0.          0.          0.        ]
Accuracy
1.0

In [5]:
dot_data = tree.export_graphviz(clf, out_file=None, filled=True, rounded=True) 
graph = pydotplus.graph_from_dot_data(dot_data)
graph.write_png('zoo.png')

True